# Generated by Django 5.1.4 on 2025-01-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_mlmuser_mlm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmuser',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
