# Generated by Django 5.1.4 on 2025-01-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_mlmuser_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payout',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
