# Generated by Django 5.1.4 on 2025-01-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_mlmuser_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmuser',
            name='custom_sponsor_id',
            field=models.CharField(default=2, editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
