# Generated by Django 5.1.4 on 2025-01-07 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_features_paymenttype_plan_planfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kyc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_aadhar_img', models.ImageField(upload_to='kyc/')),
                ('back_aadhar_img', models.ImageField(upload_to='kyc/')),
                ('front_pan_img', models.ImageField(upload_to='kyc/')),
                ('back_pan_img', models.ImageField(upload_to='kyc/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=100)),
                ('blocked', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PaymentType',
        ),
        migrations.DeleteModel(
            name='PlanFeature',
        ),
    ]
