# Generated by Django 5.1.4 on 2025-01-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_kyc_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='position',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
